
package sd.tp1.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FileServerImplWS", targetNamespace = "http://srv.tp1.sd/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FileServerImplWS {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hasAlbum", targetNamespace = "http://srv.tp1.sd/", className = "sd.tp1.ws.HasAlbum")
    @ResponseWrapper(localName = "hasAlbumResponse", targetNamespace = "http://srv.tp1.sd/", className = "sd.tp1.ws.HasAlbumResponse")
    @Action(input = "http://srv.tp1.sd/FileServerImplWS/hasAlbumRequest", output = "http://srv.tp1.sd/FileServerImplWS/hasAlbumResponse")
    public boolean hasAlbum(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listAlbums", targetNamespace = "http://srv.tp1.sd/", className = "sd.tp1.ws.ListAlbums")
    @ResponseWrapper(localName = "listAlbumsResponse", targetNamespace = "http://srv.tp1.sd/", className = "sd.tp1.ws.ListAlbumsResponse")
    @Action(input = "http://srv.tp1.sd/FileServerImplWS/listAlbumsRequest", output = "http://srv.tp1.sd/FileServerImplWS/listAlbumsResponse")
    public List<String> listAlbums();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     * @throws NoAlbumFoundException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hasPicture", targetNamespace = "http://srv.tp1.sd/", className = "sd.tp1.ws.HasPicture")
    @ResponseWrapper(localName = "hasPictureResponse", targetNamespace = "http://srv.tp1.sd/", className = "sd.tp1.ws.HasPictureResponse")
    @Action(input = "http://srv.tp1.sd/FileServerImplWS/hasPictureRequest", output = "http://srv.tp1.sd/FileServerImplWS/hasPictureResponse", fault = {
        @FaultAction(className = NoAlbumFoundException_Exception.class, value = "http://srv.tp1.sd/FileServerImplWS/hasPicture/Fault/NoAlbumFoundException")
    })
    public boolean hasPicture(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1)
        throws NoAlbumFoundException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws NoAlbumFoundException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listPicturesFromAlbum", targetNamespace = "http://srv.tp1.sd/", className = "sd.tp1.ws.ListPicturesFromAlbum")
    @ResponseWrapper(localName = "listPicturesFromAlbumResponse", targetNamespace = "http://srv.tp1.sd/", className = "sd.tp1.ws.ListPicturesFromAlbumResponse")
    @Action(input = "http://srv.tp1.sd/FileServerImplWS/listPicturesFromAlbumRequest", output = "http://srv.tp1.sd/FileServerImplWS/listPicturesFromAlbumResponse", fault = {
        @FaultAction(className = NoAlbumFoundException_Exception.class, value = "http://srv.tp1.sd/FileServerImplWS/listPicturesFromAlbum/Fault/NoAlbumFoundException")
    })
    public List<String> listPicturesFromAlbum(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws NoAlbumFoundException_Exception
    ;

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "createAlbum", targetNamespace = "http://srv.tp1.sd/", className = "sd.tp1.ws.CreateAlbum")
    @ResponseWrapper(localName = "createAlbumResponse", targetNamespace = "http://srv.tp1.sd/", className = "sd.tp1.ws.CreateAlbumResponse")
    @Action(input = "http://srv.tp1.sd/FileServerImplWS/createAlbumRequest", output = "http://srv.tp1.sd/FileServerImplWS/createAlbumResponse")
    public void createAlbum(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @throws NoAlbumFoundException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteAlbum", targetNamespace = "http://srv.tp1.sd/", className = "sd.tp1.ws.DeleteAlbum")
    @ResponseWrapper(localName = "deleteAlbumResponse", targetNamespace = "http://srv.tp1.sd/", className = "sd.tp1.ws.DeleteAlbumResponse")
    @Action(input = "http://srv.tp1.sd/FileServerImplWS/deleteAlbumRequest", output = "http://srv.tp1.sd/FileServerImplWS/deleteAlbumResponse", fault = {
        @FaultAction(className = NoAlbumFoundException_Exception.class, value = "http://srv.tp1.sd/FileServerImplWS/deleteAlbum/Fault/NoAlbumFoundException")
    })
    public void deleteAlbum(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws NoAlbumFoundException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @throws NoPictureFoundException_Exception
     * @throws NoAlbumFoundException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deletePicture", targetNamespace = "http://srv.tp1.sd/", className = "sd.tp1.ws.DeletePicture")
    @ResponseWrapper(localName = "deletePictureResponse", targetNamespace = "http://srv.tp1.sd/", className = "sd.tp1.ws.DeletePictureResponse")
    @Action(input = "http://srv.tp1.sd/FileServerImplWS/deletePictureRequest", output = "http://srv.tp1.sd/FileServerImplWS/deletePictureResponse", fault = {
        @FaultAction(className = NoAlbumFoundException_Exception.class, value = "http://srv.tp1.sd/FileServerImplWS/deletePicture/Fault/NoAlbumFoundException"),
        @FaultAction(className = NoPictureFoundException_Exception.class, value = "http://srv.tp1.sd/FileServerImplWS/deletePicture/Fault/NoPictureFoundException")
    })
    public void deletePicture(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1)
        throws NoAlbumFoundException_Exception, NoPictureFoundException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns byte[]
     * @throws NoPictureFoundException_Exception
     * @throws NoAlbumFoundException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPicture", targetNamespace = "http://srv.tp1.sd/", className = "sd.tp1.ws.GetPicture")
    @ResponseWrapper(localName = "getPictureResponse", targetNamespace = "http://srv.tp1.sd/", className = "sd.tp1.ws.GetPictureResponse")
    @Action(input = "http://srv.tp1.sd/FileServerImplWS/getPictureRequest", output = "http://srv.tp1.sd/FileServerImplWS/getPictureResponse", fault = {
        @FaultAction(className = NoAlbumFoundException_Exception.class, value = "http://srv.tp1.sd/FileServerImplWS/getPicture/Fault/NoAlbumFoundException"),
        @FaultAction(className = NoPictureFoundException_Exception.class, value = "http://srv.tp1.sd/FileServerImplWS/getPicture/Fault/NoPictureFoundException")
    })
    public byte[] getPicture(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1)
        throws NoAlbumFoundException_Exception, NoPictureFoundException_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @throws NoAlbumFoundException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "uploadPicture", targetNamespace = "http://srv.tp1.sd/", className = "sd.tp1.ws.UploadPicture")
    @ResponseWrapper(localName = "uploadPictureResponse", targetNamespace = "http://srv.tp1.sd/", className = "sd.tp1.ws.UploadPictureResponse")
    @Action(input = "http://srv.tp1.sd/FileServerImplWS/uploadPictureRequest", output = "http://srv.tp1.sd/FileServerImplWS/uploadPictureResponse", fault = {
        @FaultAction(className = NoAlbumFoundException_Exception.class, value = "http://srv.tp1.sd/FileServerImplWS/uploadPicture/Fault/NoAlbumFoundException")
    })
    public void uploadPicture(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        byte[] arg2)
        throws NoAlbumFoundException_Exception
    ;

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "checkNumberOfPhotos", targetNamespace = "http://srv.tp1.sd/", className = "sd.tp1.ws.CheckNumberOfPhotos")
    @ResponseWrapper(localName = "checkNumberOfPhotosResponse", targetNamespace = "http://srv.tp1.sd/", className = "sd.tp1.ws.CheckNumberOfPhotosResponse")
    @Action(input = "http://srv.tp1.sd/FileServerImplWS/checkNumberOfPhotosRequest", output = "http://srv.tp1.sd/FileServerImplWS/checkNumberOfPhotosResponse")
    public int checkNumberOfPhotos();

}
