
package sd.tp1.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "NoPictureFoundException", targetNamespace = "http://srv.tp1.sd/")
public class NoPictureFoundException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private NoPictureFoundException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public NoPictureFoundException_Exception(String message, NoPictureFoundException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public NoPictureFoundException_Exception(String message, NoPictureFoundException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: sd.tp1.ws.NoPictureFoundException
     */
    public NoPictureFoundException getFaultInfo() {
        return faultInfo;
    }

}
